
def change_theme(self, theme_index):
    if theme_index == 1:
        # Ставиться відповідна тема
        self.setStyleSheet(u"QWidget {\n"
                                 "    background-color: #F5FFFA;\n"
                                 "    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n"
                                 "    font-size: 16px;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: rgb(203, 236, 199);\n"
                                 "    border: none;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: rgb(232, 199, 236)\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(199, 221, 236)\n"
                                 "}\n"
                                 "QListView {\n"
                                 "    background-color: #FFF5EE;\n"
                                 "    border: 5px solid rgb(199, 221, 236);\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    border: 1px solid rgb(199, 221, 236);\n"
                                 "	background-color: rgb(203, 236, 199);\n"
                                 "    height: 5px;\n"
                                 "    margin: 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background-color: rgb(236, 213, 199);\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 10px;\n"
                                 "    width: 10px;\n"
                                 "    margin: -15px 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:vertical {\n"
                                 "    background-color: rgb(236, 213, 199);\n"
                                 ""
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 20px;\n"
                                 "    }\n"
                                 "QSlider::groove:vertical {\n"
                                 "    border: 1px solid rgb(199, 221, 236);\n"
                                 "	background-color: rgb(203, 236, 199);\n"
                                 "	width: 10px;\n"
                                 "    margin: 0px;\n"
                                 "    }")
    elif theme_index == 2:
        self.setStyleSheet(u"QWidget {\n"
                                 "    background-color: #f2f2f2;\n"
                                 "    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n"
                                 "    font-size: 16px;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: #cccccc;\n"
                                 "    border: none;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #b3b3b3;\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #999999\n"
                                 "}\n"
                                 "QListView {\n"
                                 "    background-color: #e6e6e6;\n"
                                 "    border: 5px solid grey;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    border: 1px solid #636363;\n"
                                 "	background-color: #808080;\n"
                                 "    height: 5px;\n"
                                 "    margin: 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background-color: #000000;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 10px;\n"
                                 "    width: 10px;\n"
                                 "    margin: -15px 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:vertical {\n"
                                 "    background-color: #000000;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 20px;\n"
                                 "    }\n"
                                 "QSlider::g"
                                 "roove:vertical {\n"
                                 "    border: 1px solid #636363;\n"
                                 "	background-color: #808080;\n"
                                 "	width: 10px;\n"
                                 "    margin: 0px;\n"
                                 "    }")
    elif theme_index == 3:
        self.setStyleSheet(u"QWidget {\n"
                                 "    background-color: #c2f0c2;\n"
                                 "    \n"
                                 "    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n"
                                 "    font-size: 16px;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: #70db70;\n"
                                 "    border: none;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #33cc33;\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #1f7a1f\n"
                                 "}\n"
                                 "QListView {\n"
                                 "    background-color: #d6f5d6;\n"
                                 "    border: 5px solid #248f24;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    border: 1px solid #2eb82e;\n"
                                 "	background-color: #248f24;\n"
                                 "    height: 5px;\n"
                                 "    margin: 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background-color: #000000;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 10px;\n"
                                 "    width: 10px;\n"
                                 "    margin: -15px 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:vertical {\n"
                                 "    background-color: #000000;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 20px;\n"
                                 "    }\n"
                                 "Q"
                                 "Slider::groove:vertical {\n"
                                 "    border: 1px solid #2eb82e;\n"
                                 "	background-color: #248f24;\n"
                                 "	width: 10px;\n"
                                 "    margin: 0px;\n"
                                 "    }")
    elif theme_index == 0:
        self.setStyleSheet(u"QWidget {\n"
                                 "    background-color: #e6f2ff;\n"
                                 "    \n"
                                 "    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n"
                                 "    font-size: 16px;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: #b3d9ff;\n"
                                 "    border: none;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #3399ff;\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #0066cc;\n"
                                 "}\n"
                                 "QListView {\n"
                                 "    background-color: #99ccff;\n"
                                 "    border: 5px solid #001a33;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    border: 1px solid #99ccff;\n"
                                 "	background-color: white;\n"
                                 "    height: 5px;\n"
                                 "    margin: 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background-color: white;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 10px;\n"
                                 "    width: 10px;\n"
                                 "    margin: -15px 0px;\n"
                                 "    }\n"
                                 "QSlider::handle:vertical {\n"
                                 "    background-color: #000000;\n"
                                 "    border: none;\n"
                                 "	border-radius: 10px;\n"
                                 "    height: 20px;\n"
                                 "    }\n"
                                 ""
                                 "QSlider::groove:vertical {\n"
                                 "    border: 1px solid #99ccff;\n"
                                 "	background-color: white;\n"
                                 "	width: 10px;\n"
                                 "    margin: 0px;\n"
                                 "    }")